
export let sampleData: Object[] = [
    {
        taskID:1,
        taskName: "sample",
        startDate: new Date("02/03/2017"),
        endDate: new Date("02/03/2017"),
        progress: 100,
        duration: 5,
        priority:'Normal',
        approved: false,
        isInExpandState : true,
        subtasks:[
            {
                taskID:1,
                taskName: "sample",
                startDate: new Date("02/03/2017"),
                endDate: new Date("02/03/2017"),
                progress: 100,
                duration: 5,
                priority:'Normal',
                approved: false,
                isInExpandState : true,
            },
            {
                taskID:2,
                taskName: "sample",
                startDate: new Date("02/03/2017"),
                endDate: new Date("02/03/2017"),
                progress: 100,
                duration: 5,
                priority:'Normal',
                approved: false,
                isInExpandState : true,
            },
            {
                taskID:3,
                taskName: "sample",
                startDate: new Date("02/03/2017"),
                endDate: new Date("02/03/2017"),
                progress: 100,
                duration: 5,
                priority:'Normal',
                approved: false,
                isInExpandState : true,
            },
            {
                taskID:4,
                taskName: "sample",
                startDate: new Date("02/03/2017"),
                endDate: new Date("02/03/2017"),
                progress: 100,
                duration: 5,
                priority:'Normal',
                approved: false,
                isInExpandState : true,
            },
            {
                taskID:5,
                taskName: "sample",
                startDate: new Date("02/03/2017"),
                endDate: new Date("02/03/2017"),
                progress: 100,
                duration: 5,
                priority:'Normal',
                approved: false,
                isInExpandState : true,
            }
        ]
    },
    {
        taskID:6,
        taskName: "sample",
        startDate: new Date("02/03/2017"),
        endDate: new Date("02/03/2017"),
        progress: 100,
        duration: 5,
        priority:'High',
        approved: false,
        isInExpandState : false
    }
]